### ISSUE TITLE
Tests failing but passing

### ISSUE THREAD

**Issue by necromeo** [technologicalMayhem/human-date-parser#8]
Hi!

I was looking into some odd behavior in Nushell's datetime parsing, specifically for "In" and "Ago" dates. Turns out the issue was originating here, in the library being used by Nushell.

There seems to be a problem with the test assertion, where negative values are interpreted as correct when they shouldn't be. 
Running all the tests only shows the "A year ago" test failing. However, changing the assertion to
```rust
assert!((result - expected).abs() < Duration::milliseconds(10)); // notice the abs()
```
reveals that there are some other tests, rightfully, failing.

Is this a known issue?

---

Here's the full test run:

```
running 39 tests
test tests::fail_parse_20231131 ... ok
test tests::parse_10_hours_and_5_minutes_ago ... ok
test tests::parse_10_seconds_ago ... ok
test tests::parse_12_hours_ago_at_today ... FAILED
test tests::parse_12_hours_ago_at_0400 ... FAILED
test tests::parse_1520_friday ... ok
test tests::parse_1325_next_tuesday ... FAILED
test tests::parse_12_hours_ago_at_7_days_ago ... ok
test tests::parse_1_years_2_months_3_weeks_5_days_8_hours_17_minutes_and_45_seconds_ago ... FAILED
test tests::parse_1_year_1_month_1_week_1_day_1_hour_1_minute_and_1_second_ago ... FAILED
test tests::parse_20221107_132530 ... ok
test tests::parse_2_hours_32_minutes_and_7_seconds_ago ... ok
test tests::parse_7_days_ago_at_0400 ... ok
test tests::parse_a_day_ago ... ok
test tests::parse_a_minute_ago ... ok
test tests::parse_a_month_ago ... ok
test tests::parse_a_second_ago ... ok
test tests::parse_7_days_ago_at_7_days_ago ... ok
test tests::parse_a_week_ago ... ok
test tests::parse_a_year_ago ... FAILED
test tests::parse_an_hour_ago ... ok
test tests::parse_in_2_hours ... ok
test tests::parse_in_5_minutes_and_30_seconds ... ok
test tests::parse_last_friday_at_1945 ... ok
test tests::parse_last_week ... ok
test tests::parse_now ... ok
test tests::parse_overmorrow_1830 ... ok
test tests::parse_last_week_tuesday ... ok
test tests::parse_this_friday_1700 ... FAILED
test tests::parse_in_3_days ... ok
test tests::parse_overmorrow ... ok
test tests::parse_this_week ... ok
test tests::parse_this_week_monday ... ok
test tests::parse_next_week ... ok
test tests::parse_tomorrow_1830 ... ok
test tests::parse_today_1830 ... ok
test tests::parse_next_week_monday ... ok
test tests::parse_yesterday_1830 ... ok
test tests::parse_this_week_friday ... ok

failures:

---- tests::parse_12_hours_ago_at_today stdout ----
Result: 2009-12-31 12:00:00 -03:00
Expected: 2010-12-31 12:00:00 -03:00
Note: Maximum difference between these values allowed is 10ms.
thread 'tests::parse_12_hours_ago_at_today' panicked at src/lib.rs:511:5:
assertion failed: (result - expected).abs() < Duration::milliseconds(10)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- tests::parse_12_hours_ago_at_0400 stdout ----
Result: 2009-12-31 16:00:00 -03:00
Expected: 2010-12-31 16:00:00 -03:00
Note: Maximum difference between these values allowed is 10ms.
thread 'tests::parse_12_hours_ago_at_0400' panicked at src/lib.rs:511:5:
assertion failed: (result - expected).abs() < Duration::milliseconds(10)

---- tests::parse_1325_next_tuesday stdout ----
Result: 2010-01-05 13:25:00 -03:00
Expected: 2010-01-12 13:25:00 -03:00
Note: Maximum difference between these values allowed is 10ms.
thread 'tests::parse_1325_next_tuesday' panicked at src/lib.rs:511:5:
assertion failed: (result - expected).abs() < Duration::milliseconds(10)

---- tests::parse_1_years_2_months_3_weeks_5_days_8_hours_17_minutes_and_45_seconds_ago stdout ----
Result: 2008-10-07 15:42:15 -03:00
Expected: 2008-10-07 16:42:15 -03:00
Note: Maximum difference between these values allowed is 10ms.
thread 'tests::parse_1_years_2_months_3_weeks_5_days_8_hours_17_minutes_and_45_seconds_ago' panicked at src/lib.rs:511:5:
assertion failed: (result - expected).abs() < Duration::milliseconds(10)

---- tests::parse_1_year_1_month_1_week_1_day_1_hour_1_minute_and_1_second_ago stdout ----
Result: 2008-11-22 23:58:59 -02:00
Expected: 2008-11-23 22:58:59 -02:00
Note: Maximum difference between these values allowed is 10ms.
thread 'tests::parse_1_year_1_month_1_week_1_day_1_hour_1_minute_and_1_second_ago' panicked at src/lib.rs:511:5:
assertion failed: (result - expected).abs() < Duration::milliseconds(10)

---- tests::parse_a_year_ago stdout ----
Result: 2009-01-01 01:00:00 -02:00
Expected: 2009-01-01 00:00:00 -02:00
Note: Maximum difference between these values allowed is 10ms.
thread 'tests::parse_a_year_ago' panicked at src/lib.rs:511:5:
assertion failed: (result - expected).abs() < Duration::milliseconds(10)

---- tests::parse_this_friday_1700 stdout ----
Result: 2010-01-01 17:00:00 -03:00
Expected: 2010-01-08 17:00:00 -03:00
Note: Maximum difference between these values allowed is 10ms.
thread 'tests::parse_this_friday_1700' panicked at src/lib.rs:511:5:
assertion failed: (result - expected).abs() < Duration::milliseconds(10)


failures:
    tests::parse_12_hours_ago_at_0400
    tests::parse_12_hours_ago_at_today
    tests::parse_1325_next_tuesday
    tests::parse_1_year_1_month_1_week_1_day_1_hour_1_minute_and_1_second_ago
    tests::parse_1_years_2_months_3_weeks_5_days_8_hours_17_minutes_and_45_seconds_ago
    tests::parse_a_year_ago
    tests::parse_this_friday_1700

test result: FAILED. 32 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```
I'm not much of Rust dev, but will try to look a bit into this.

**Comment by technologicalMayhem** [comment]
Since #9 is merge, I am gonna close this.
